=== hrldrm/Shelf/data/ShelfSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">

<!-- Attributes BEGIN -->
  <xs:attribute name="Category">
    <xs:simpleType>
      <xs:restriction base="xs:string">
            <xs:enumeration value="Religion"/>
            <xs:enumeration value="Young Adult"/>
        <xs:enumeration value="Mystery/Thriller"/>
            <xs:enumeration value="Non-fiction"/>
            <xs:enumeration value="Fantasy"/>
            <xs:enumeration value="Romance"/>
            <xs:enumeration value="Sci-fi"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
<!-- Attributes END -->

<!--Review BEGIN -->
  <xs:complexType name="Reviews">
      <xs:sequence>
          <xs:element ref="Vote"/>
          <xs:element name="Date" type="xs:date"/>
          <xs:element ref="Reviewer"/>
          <xs:element ref="ReviewContent"/>
      </xs:sequence>
  </xs:complexType>

    <xs:element name="Vote">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="-1|1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="ReviewContent">
        <xs:simpleType>
            <xs:restriction base="xs:string">
        <xs:minLength value="20"/>
        <xs:maxLength value="1000"/>
      </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="Reviewer" type="xs:string"/>
<!--Review END--> 

    <xs:element name="Price">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="6"/>
                <xs:fractionDigits value="2"/>
                <xs:minExclusive value="0"/>
                <xs:maxExclusive value="1600"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

  <xs:element name="Author">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="FName" type="xs:string"/>
        <xs:element name="MInit" type="xs:string" nillable="true"/>
        <xs:element name="LName" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  
<!--Publishing BEGIN -->
  <xs:complexType name="PublicationDetails">
    <xs:sequence>
      <xs:element name="PublicationHouse" type="xs:string" minOccurs="1" maxOccurs="1"/>
          <xs:element name="PublishingDate" type="xs:date" maxOccurs="1" />
          <xs:element name="ISBN" type="ISBN" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
<!-- Publishing END -->

<!--ISBN BEGIN-->
  <xs:complexType name="ISBN">
    <xs:sequence>
      <xs:element ref="PrefixElem" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="RegGroupElem" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="RegistrantElem" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="PubElem" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="CheckDigit" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="PrefixElem">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="978"/>
        <xs:enumeration value="979"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="RegGroupElem">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99999"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="RegistrantElem">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="9999999"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="PubElem">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="999999"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="CheckDigit">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="9"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
<!--ISBN END-->

<!--Publishing END -->
  <xs:complexType name="BookInfo">
      <xs:sequence>
          <xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
          <xs:element ref="Author" minOccurs="1" maxOccurs="unbounded"/>
          <xs:element name="PublicationDetails" type="PublicationDetails" minOccurs="1" maxOccurs="1"/>
      <xs:element name="PageCount">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MediaType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Paperback"/>
            <xs:enumeration value="Hardcover"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Synopsis" minOccurs="1" maxOccurs="1"> 
        <xs:simpleType>
                <xs:restriction base="xs:string">
            <xs:minLength value="20"/>
          </xs:restriction>
            </xs:simpleType>
          </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Book">
      <xs:sequence>
        <xs:element name="ID" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:totalDigits value="3"/>
                    <xs:minExclusive value="0"/>
                    <xs:maxExclusive value="1000"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Info" type="BookInfo" minOccurs="1"/>
        <xs:element ref="Price"/>
        <xs:element name="AverageVotes" default="0" maxOccurs="1">
            <xs:simpleType>
              <xs:restriction base="xs:decimal"/>
            </xs:simpleType>
          </xs:element>
          <xs:element name="Review" type="Reviews" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="Category"/>
  </xs:complexType>
  
  <xs:element name="BookStore">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="Book" type="Book" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
      </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="BookID">
        <xs:restriction base="xs:integer">
          <xs:totalDigits value="3"/>
                <xs:minExclusive value="0"/>
                <xs:maxExclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="BookShelf">
      <xs:sequence>
        <xs:element name="ShelfName" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="ID" type="BookID" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="BookCart">
        <xs:sequence>
          <xs:element name="ID" type="BookID" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="UserInfo">
        <xs:sequence>
            <xs:element name="UserID" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="FirstName" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="LastName" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Email" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="VerifiedEmail" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
            <xs:element name="EncryptedPass" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Hash" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Shelves">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Shelf" type="BookShelf" minOccurs="0" maxOccurs="unbounded"/>      
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="Cart" type="BookCart" minOccurs="1" maxOccurs="1"/>
            <xs:element name="RatedBooks" minOccurs="1" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Rating" minOccurs="0" maxOccurs="105">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="ID" type="BookID" minOccurs="1" maxOccurs="1"/>
                        <xs:element ref="Vote"/> 
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Info" type="UserInfo"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Users">
      <xs:complexType>
          <xs:sequence>
              <xs:element ref="User" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== hrldrm/Shelf/data/Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ShelfSchema.xsd">
<User><Info><UserID>59303167bd192</UserID><FirstName>Virgilio</FirstName><LastName>Mendoza</LastName><Email>virgiliomendoza05@gmail.com</Email><VerifiedEmail>true</VerifiedEmail><Hash>109a0ca3bc27f3e96597370d5c8cf03d</Hash><EncryptedPass>+Q6W0gD7cAd3HFritqzf3nDmWZkEnRyjtu81lnAXtk/2mbebbINi7Y1Q+ycbH57PqrGoMcX1t8YWhOkLNXUIWg==</EncryptedPass><Shelves/><Cart/><RatedBooks/></Info></User></Users>
